### PR TITLE
Feat: add sextant-based fonts

### PR DESCRIPTION
**Pull request by p0kR**
**Note: This Pull Request is still work in progress**

With this Pull Request I want to add two new Fonts based on the unicode Sextants from the block "[mosaic terminal graphic characters](https://www.unicode.org/charts/nameslist/n_1FB00.html)".

As the calculations for rendering may become more difficult for those pixel sizes (no dividers of 8), a few things have to be adapted all over the rendering code.  Therefore this MR might take some time.

### CODE REVIEW

**Comment by p0kR** [comment]
I created another pull request for the failing CI check.

https://github.com/joshka/tui-big-text/pull/27

**Comment by p0kR** [comment]
I got it working for sextant based sizes, I think.
I will later push my changes, but I still have to check some things.

One thing I found:
As the sextant-unicode-symbols are part of a newer unicode version and are rendered differently for different terminals and or fonts, those are currently not very portable.

Here are two examples with the same font in two different terminal (first is Free Mono in my Gnome Terminal; second is Free Mono in my VS Code Terminal):
grafik
grafik

The problem I see is that the sextant based symbols are rendered wider that the other symbols of the terminal and are overlapping.
This can be seen when using those symbols in the editor:
grafik
(This is the exact code used to create toe outputs above)

**Comment by p0kR** [comment]
**UPDATE:** I refactored the code, that I was able to add unit tests for those previously uncovered lines.

---

There are currently two defensive checks in `render_glyph()` not covered.
Is there a way to manually mark them as OK or something?

If you want, you can have a look yourself here:
- [Line 333](https://github.com/joshka/tui-big-text/pull/26/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R333)
- [Line 353](https://github.com/joshka/tui-big-text/pull/26/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R353)

**Comment by p0kR** [comment]
I also updated the example, but I could not get `VHS` to render the new pixel sizes correctly (although it works in my terminal).
I already set a different font in the tape file. I looks better, but still ugly.

@joshka maybe it works, when you try it on your machine. Or do you know a different trick?

---

**Edit:** I get this ugly presentation only in VS Code and when using VHS. In my default Gnome Terminal, this PixelSize works as expected. (See also https://github.com/joshka/tui-big-text/pull/26#issuecomment-1913355288 )  
I added a highlighted note to the affected PixelSize sizes/fonts.
I would suggest to merge this as is, if you don't find any more issues to be solved.

**Comment by joshka** [comment]
I tweaked the example code a bit. Free Mono is a bit wide for my taste on this (and I like to try to make the images work within the constraints of how github renders readme files - so tend to want something in the 1200 max width range.

  Made with VHS

I added a note about font compatibility in the readme.

**Comment by joshka** [comment]
Thanks for the PR and apologies on taking so long to jump into this. I've merged this just now and will push a release shortly

**Pull request merged**
